### ISSUE TITLE
Platform refactoring and extension for future use

### ISSUE THREAD

**Issue by sbuckpesch** [apparena/patterns#45]
### Description

The pattern platform should be extended to be the central place for:

1. Software patterns (React)
2. Software documentation
3. Corporate Identity
4. Corporate Communication Guidelines

### Refactoring steps
To reach that goal we need to refactor the repository and fullfil the following tasks:

1. Content/Pages/Navigation need to be extended easily by "Non-Devs" (slight(!) knowledge of React can be expected)
2. Clear code structure (kick out patternlab, build, public, source, docs folders, ...)
3. Working build scripts in package.json
4. Automated tests on TravisCI (Continous integration)
    - Automatically build, test and deploy Pull requests on a staging environment
    - Automatically build, test and deploy changes to the master branch to the production environment
5. Documentation in Readme.md helps a new contributer with his local setup and contribution with no hassle. (Use this template:  https://gist.github.com/PurpleBooth/109311bb0361f32d87a2
    - Add a markdown file for each of the 4 areas on top. Each area needs to have a documented introduction how to maintain it.
6. Add a docker-compose file that will provide a running environment by just typing `docker-compose up`
7. Deployment (Automated deployment including AWS cloudfront cache invalidation)

**Comment by vklein** [comment]
@sbuckpesch 
In my opinion Refactoring step 6 does not make sense. We dont need database, redis or other enviroments.

It should be just to add a `yarn start` script, which starts a server for local developing with webpack hot reload.

**Comment by BrandtM** [comment]
Refactoring is now completed and has been deployed to NPM.
